### PR TITLE
fix invalid options --no-ri --no-doc

### PR DESCRIPTION
**Pull request by ivangabriele**
Replace deprecated  `--no-ri --no-doc` by `--no-document`.

### CODE REVIEW

**Comment by thibaudcolas** [comment]
Just stumbled upon this today while trying to install the CLI with Ruby v2.6.1.

Here are the errors for reference:

```
$ gem install travis -v 1.8.9 --no-rdoc --no-ri
ERROR:  While executing gem ... (OptionParser::InvalidOption)
    invalid option: --no-rdoc

✘1 $ gem install travis -v 1.8.9 --no-ri
ERROR:  While executing gem ... (OptionParser::InvalidOption)
    invalid option: --no-ri
```

**Comment by douglascayers** [comment]
Fixes https://github.com/travis-ci/travis.rb/issues/646

**Comment by varsnotwars** [comment]
ACK. Tested on Windows 10.

**Comment by BanzaiMan** [comment]
Sorry about that. We merged #707 instead.

**Pull request closed without merging**
