### PR TITLE
Adds support for received state

### PR DESCRIPTION
**Pull request by jschneiderhan**
See https://github.com/travis-ci/travis.rb/issues/283 for more info

### CODE REVIEW

**Comment by jschneiderhan** [comment]
Tests were already failing on master, so this will probably need to be rebased off master and re-built at some point.

**Comment by jschneiderhan** [comment]
I made a few assumptions on where "received" should be included, so this may need a bit of re-work

**Comment by joshk** [comment]
We will review this PR asap.

**Comment by jschneiderhan** [comment]
@joshk great, thank you! If i can help any more let me know. Also, if anyone has any workaround ideas I'd be glad to hear them. Our continuous deployment process makes use of the event listener, so getting it working again is high-priority for us. Worst-case: we can run off a fork until this is resolved.

**Pull request merged**
