### PR TITLE
Update .travis.yml and adapt to HighLine 2.0

### PR DESCRIPTION
**Pull request by abinoam**
~A work in progress...~

---

(29/09/17 Edit)

This PR:
* Adapt code to use HighLine 2.0.
* Fix travis configuration:
  - Fix for JRuby
  - Fix for 1.9
  - Add Ruby 2.3, 2.4 and ruby-head (currently 2.5.0dev)
  - Add Rubinius
  - Reduce MacOS testing to one ruby version

### CODE REVIEW

**Comment by abinoam** [comment]
Hi @rkh,

HighLine will be releasing version 2.0 soon. And this PR make travis.rb compatible with it.

Pre release announcemnt at: http://blade.nagaokaut.ac.jp/cgi-bin/scat.rb/ruby/ruby-talk/438283

**Comment by abinoam** [comment]
I have made a new develop release of HighLine that eases the transition.
Updated this PR to reflect the changes.

**Comment by BanzaiMan** [comment]
Hello, there.

Sorry for such a long silence. If you are still interested in this PR, please remove unnecessary changes to `.travis.yml` and `travis.gemspec` (because the latter will be generated).

Otherwise, we will look at moving to Highline 2.0 in the near future.

**Comment by abinoam** [comment]
I'll try to rebase, fix and resolve conflicts.

**Comment by BanzaiMan** [comment]
Great. I believe this would allows to support Ruby 2.7.

**Comment by abinoam** [comment]
Hi @BanzaiMan,

I see you have already fixed it on branch ha-ruby-2.7.
Feel free to merge it from there. No problem at all.
I'm closing this PR as it doesn't add any code that you haven't already cherry picked into that branch.

Thanks for updating travis.rb! 👍

**Pull request closed without merging**
