### PR TITLE
Message about how to install 'pry' for 'travis console'

### PR DESCRIPTION
**Pull request by HaraldNordgren**

### CODE REVIEW

**Comment by HaraldNordgren** [comment]
Could someone merge or close this one?

**Comment by HaraldNordgren** [comment]
@rkh @Turbo87 @cotsog Merge this?

**Comment by HaraldNordgren** [comment]
@BanzaiMan @carlad @joecorcoran @renee-travisci @aakritigupta @backspace Merge this?

**Comment by backspace** [comment]
Hello, @HaraldNordgren! Thanks for opening this. I was able to `gem install travis` and then `travis console` without seeming to need Pry. Were you running into a case where Pry was required?

**Comment by backspace** [comment]
Never mind my message above, I was confused and incorrect!

**Pull request merged**
