### PR TITLE
Specify required github token scopes

### LINKED ISSUE #367: Insufficient GitHub OAuth permissions yields "request method not allowed"
Attempting to login using a GitHub token which has insufficient permissions prints the error `405: "request method not allowed"`.  This is not a particularly helpful error message and indicates an errant HTTP request.  The problem results from `travis.rb` attempting to `POST` to https://travis-ci.org/insufficient_oauth_permissions#existing-user rather than directing the user to visit this URL.

To demonstrate the issue, here's an example:

    $ travis login --debug --debug-http --github-token XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    ** Loading "/home/kevin/.travis/config.yml"
    ** Loading gh
    ** GET "config"
    I, [2016-02-17T13:50:23.257060 #16521]  INFO -- : get https://api.travis-ci.org/config
    D, [2016-02-17T13:50:23.257184 #16521] DEBUG -- request: User-Agent: "Travis/1.8.2 (Debian testing like Linux; Ruby 2.2.4-p230; RubyGems 2.4.5.1; command login) Faraday/0.9.2 Typhoeus/0.8.0"
    Accept: "application/vnd.travis-ci.2+json"
    I, [2016-02-17T13:50:23.894033 #16521]  INFO -- Status: 200
    D, [2016-02-17T13:50:23.894236 #16521] DEBUG -- response: Connection: "keep-alive"
    Server: "nginx"
    Date: "Wed, 17 Feb 2016 21:50:23 GMT"
    Content-Type: "application/json"
    Content-Length: "248"
    Status: "200 OK"
    Access-Control-Allow-Origin: "*"
    Access-Control-Allow-Credentials: "true"
    Access-Control-Expose-Headers: "Content-Type, Cache-Control, Expires, Etag, Last-Modified"
    Strict-Transport-Security: "max-age=31536000"
    X-Endpoint: "Travis::Api::App::Endpoint::Home"
    X-Pattern: "/config"
    X-Oauth-Scopes: "public"
    X-Accepted-Oauth-Scopes: "public"
    Vary: "Accept,Accept-Encoding"
    X-Rack-Cache: "miss"
    Via: "1.1 vegur"
    **   took 0.64 seconds
    ** GitHub API: GET /user?per_page=100
    **   took 0.42 seconds
    ** POST "auth/github" {:github_token=>"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"}
    I, [2016-02-17T13:50:24.347303 #16521]  INFO -- : post https://api.travis-ci.org/auth/github
    D, [2016-02-17T13:50:24.347459 #16521] DEBUG -- request: User-Agent: "Travis/1.8.2 (Debian testing like Linux; Ruby 2.2.4-p230; RubyGems 2.4.5.1; command login) Faraday/0.9.2 Typhoeus/0.8.0"
    Accept: "application/vnd.travis-ci.2+json"
    Content-Type: "application/x-www-form-urlencoded"
    I, [2016-02-17T13:50:24.561371 #16521]  INFO -- Status: 302
    D, [2016-02-17T13:50:24.561566 #16521] DEBUG -- response: Connection: "keep-alive"
    Server: "nginx"
    Date: "Wed, 17 Feb 2016 21:50:24 GMT"
    Content-Type: "application/json"
    Content-Length: "0"
    Status: "302 Found"
    Access-Control-Allow-Origin: "*"
    Access-Control-Allow-Credentials: "true"
    Access-Control-Expose-Headers: "Content-Type, Cache-Control, Expires, Etag, Last-Modified"
    Strict-Transport-Security: "max-age=31536000"
    X-Endpoint: "Travis::Api::App::Endpoint::Authorization"
    X-Pattern: "/github"
    X-Oauth-Scopes: "public"
    X-Accepted-Oauth-Scopes: "public"
    Vary: "Accept,Accept-Encoding"
    Location: "https://travis-ci.org/insufficient_oauth_permissions#existing-user"
    X-Rack-Cache: "invalidate, pass"
    Via: "1.1 vegur"
    **   took 0.22 seconds
    ** POST "https://travis-ci.org/insufficient_oauth_permissions#existing-user"
    **   took 0.43 seconds
    405: "request method not allowed"

This is arguably a defect of the API.  I'd consider 403 (or something in the 400s) a more appropriate response than 302.  However, since that's debatable and other users are probably expecting the current response, I've reported the issue here.  Feel free to reassign to the API if you think that's more appropriate.

Thanks,
Kevin

### PR DESCRIPTION
**Pull request by fiacc**
fixes #367

### CODE REVIEW

**Comment by abitrolly** [comment]
Why not merged?

**Comment by fiacc** [comment]
No idea, I closed it because it hadn't moved in 6 months, assumed it was unwanted.

**Comment by abitrolly** [comment]
`public_repo` was enough for me. Maybe that's the reason it was declined?

**Comment by hans-d** [comment]
github token permissions are still needing documentation.
There also seems to be a difference between the token needed for `travis login` and `travis login --pro`

**Comment by Al-un** [comment]
@fiacc I added a [comment](https://github.com/travis-ci/travis.rb/issues/367#issuecomment-439856716) on the issue you address. I don't know if it is because I have a travis-ci.com account instead of travis-ci.org but `repo` scope is enough for me. I do not need to add `user:email`

**Pull request closed without merging**
